In [1]:
import torch

In [6]:
#now lets start with first the autograd
#with basic example

import torch

w = torch.tensor(2.0, requires_grad=True)

x = torch.tensor(3.0)

target = torch.tensor(10.0)

pred = w * x

loss = (pred - target)**2

loss.backward()

print("loss =", loss.item(),loss)

print("gradient =", w.grad)

print(x.grad) #because we ot places the reqires_gradc on it

loss = 16.0 tensor(16., grad_fn=<PowBackward0>)
gradient = tensor(-24.)
None


In [2]:
import torch
from torch import nn

In [9]:
class net(nn.Module):
  def __init__(self):
    #nn creation
    super().__init__()
    self.cf1=nn.Linear(4,3) #input,output nuerons
    self.cf2=nn.Linear(3,2)

model=net()

In [20]:
class Net(nn.Module):

    def __init__(self):
      #creating layers

        super().__init__()

        self.fc1 = nn.Linear(5,10)

        self.fc2 = nn.Linear(10,2)

    def  forward(self,x):
      x=self.fc1(x)
      x=self.fc2(x)   #see we passing here inputs  , as above weintialized the layers(param registered)

      return x



In [21]:
model=Net()

In [22]:
model

Net(
  (fc1): Linear(in_features=5, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=2, bias=True)
)

In [27]:
model.forward(torch.tensor([[1,2,3,4,5]],dtype=torch.float32))  #how many batches  we pass is depend on us but we have pass  the input crteria inut
#no fo column in that input

tensor([[ 1.1062, -2.1294]], grad_fn=<AddmmBackward0>)

In [30]:
model.parameters()  #we will get iterator
#now we ahve to loop over it

for i in model.parameters():
  print(i)                      #you will see per layer we will get weights , bias

#these are the ones that passes to optimizer for  doing updation

Parameter containing:
tensor([[-0.0713, -0.2343,  0.3314,  0.1247,  0.2402],
        [-0.0399,  0.1589, -0.1176, -0.1267,  0.3509],
        [ 0.3548, -0.4356,  0.3236, -0.0715,  0.3887],
        [ 0.4153, -0.0445,  0.1998,  0.3403,  0.3855],
        [ 0.1243,  0.2554,  0.0028, -0.1927, -0.0583],
        [-0.2205, -0.4204,  0.4096,  0.0141,  0.0407],
        [-0.3085, -0.2442, -0.2846,  0.4269,  0.2947],
        [ 0.3536, -0.2571, -0.0380,  0.2827,  0.3385],
        [ 0.3312, -0.2034, -0.1773,  0.3732,  0.0682],
        [ 0.1697, -0.0339,  0.1171,  0.3054, -0.3952]], requires_grad=True)
Parameter containing:
tensor([ 0.0848,  0.2791, -0.0062, -0.2063,  0.1020,  0.1571,  0.0883,  0.4460,
         0.1898,  0.0912], requires_grad=True)
Parameter containing:
tensor([[ 0.0391,  0.0392,  0.1380,  0.1976,  0.2614,  0.2690,  0.2090, -0.2337,
          0.1818,  0.1761],
        [ 0.2483, -0.1001, -0.1263, -0.2932, -0.3068, -0.0504,  0.0022, -0.1454,
         -0.2818,  0.2091]], requires_grad=Tru

In [31]:

for i in model.parameters():
  print(i.shape)

torch.Size([10, 5])
torch.Size([10])
torch.Size([2, 10])
torch.Size([2])


In [32]:
'''fc1.weight

fc1.bias

fc2.weight

fc2.bias'''

'fc1.weight\n\nfc1.bias\n\nfc2.weight\n\nfc2.bias'

In [33]:
for name,param in model.named_parameters():

    print(name,param.shape) #named parameters

fc1.weight torch.Size([10, 5])
fc1.bias torch.Size([10])
fc2.weight torch.Size([2, 10])
fc2.bias torch.Size([2])


In [35]:
for layer in model.children():

    print(layer)

#it will direct layers



Linear(in_features=5, out_features=10, bias=True)
Linear(in_features=10, out_features=2, bias=True)


In [37]:
for i in model.modules():
  print(i
        )

Net(
  (fc1): Linear(in_features=5, out_features=10, bias=True)
  (fc2): Linear(in_features=10, out_features=2, bias=True)
)
Linear(in_features=5, out_features=10, bias=True)
Linear(in_features=10, out_features=2, bias=True)


In [38]:
#the thhing is like the most important thing is Dataset  , DataLoader
from torch.utils.data import Dataset

class MyDataset(Dataset):

    def __init__(self):
        self.X = [[1],[2],[3],[4]]
        self.y = [2,4,6,8]

    def __len__(self):
        return len(self.X)

    def __getitem__(self,index):
        return self.X[index], self.y[index]

In [56]:
from torch.utils.data import Dataset,DataLoader


class Mydataset(Dataset):

  def __init__(self):
    self.x=[[1,3,4],[2,4,5],[3,6,7],[4,3,5]]
    self.y=[1,2,3,4]

  def __len__(self):
    return len(self.x)  #it returns len of data

  def __getitem__(self, index):
     return self.x[index],self.y[index]   #it knows how to retutn one at a time based on index value

#lets try

data=Mydataset()
print(data[0]) #index accesable
print(data.__getitem__(0))

print(len(data))
print(data.__len__())


#next thing is dataLoader it is like to create the  atc

loader=DataLoader(data,batch_size=2)
print(type(loader))
loader


#now lets loop over the DataLoader
for x,y in loader:
  print("x-->",x,"y-->",y
        )





([1, 3, 4], 1)
([1, 3, 4], 1)
4
4
<class 'torch.utils.data.dataloader.DataLoader'>
x--> [tensor([1, 2]), tensor([3, 4]), tensor([4, 5])] y--> tensor([1, 2])
x--> [tensor([3, 4]), tensor([6, 3]), tensor([7, 5])] y--> tensor([3, 4])


In [50]:
#next thing is dataLoader it is like to create the  atc

loader=DataLoader(data,batch_size=2)
print(type(loader))
loader

<class 'torch.utils.data.dataloader.DataLoader'>


In [51]:
#now lets loop over the DataLoader
for x,y in loader:
  print(x,y
        )

[tensor([1, 1]), tensor([3, 3]), tensor([4, 4])] tensor([1, 1])
[tensor([1, 1]), tensor([3, 3]), tensor([4, 4])] tensor([1, 1])


In [54]:
''''loader = DataLoader(data, batch_size=2)
for batch_indices in [[0,1], [2,3]]:

    batch_x = []
    batch_y = []

    for idx in batch_indices:
        x, y = data[idx]   # calls __getitem__
        batch_x.append(x)
        batch_y.append(y)

    yield batch_x, batch_y'''

#internal mechanism look like this

"'loader = DataLoader(data, batch_size=2)\nfor batch_indices in [[0,1], [2,3]]:\n    \n    batch_x = []\n    batch_y = []\n\n    for idx in batch_indices:\n        x, y = data[idx]   # calls __getitem__\n        batch_x.append(x)\n        batch_y.append(y)\n\n    yield batch_x, batch_y"

In [58]:
#the prooblem that is wring here isthe collate function
#see  here tye collate done wronlht  it doen transpose so we got output liek that
#but by deafault if w euse tenspr tehn it will smoothly

from torch.utils.data import Dataset,DataLoader
import torch

class Mydataset(Dataset):

  def __init__(self):
    self.x=[[1,3,4],[2,4,5],[3,6,7],[4,3,5]]
    self.y=[1,2,3,4]

  def __len__(self):
    return len(self.x)  #it returns len of data

  def __getitem__(self, index):
     return torch.tensor(self.x[index],dtype=torch.float32),torch.tensor(self.y[index])   #it knows how to retutn one at a time based on index value

#lets try

data=Mydataset()
print(data[0]) #index accesable
print(data.__getitem__(0))

print(len(data))
print(data.__len__())


#next thing is dataLoader it is like to create the  atc

loader=DataLoader(data,batch_size=2)
print(type(loader))
loader


#now lets loop over the DataLoader
for x,y in loader:
  print("x-->",x,"y-->",y
        )


#we can ccrate our own collate function too

(tensor([1., 3., 4.]), tensor(1))
(tensor([1., 3., 4.]), tensor(1))
4
4
<class 'torch.utils.data.dataloader.DataLoader'>
x--> tensor([[1., 3., 4.],
        [2., 4., 5.]]) y--> tensor([1, 2])
x--> tensor([[3., 6., 7.],
        [4., 3., 5.]]) y--> tensor([3, 4])


In [59]:


from torch.utils.data import Dataset,DataLoader,TensorDataset
X = torch.tensor([[1],[2],[3]])
y = torch.tensor([[2],[4],[6]])

dataset = TensorDataset(X,y)

In [65]:
print(dataset[2])


        #like we can use this TensorDataset when the daat  is very low  , less size so taht w ecn load evrything evrythig into ram
#custom dataset whn we want load from disk

from torch.utils.data import Dataset

class ImageDataset(Dataset):

    def __init__(self,image_paths,labels):

        self.image_paths=image_paths
        self.labels=labels

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self,index):

        image = read_image(
            self.image_paths[index]
        )

        label = self.labels[index]

        return image,label


(tensor([3]), tensor([6]))


In [72]:
#now lest buld the real linear model

from torch.utils.data import TensorDataset,DataLoader
from torch.nn import MSELoss,Tanh,ReLU
from torch.optim import Adam
from torch import nn

#now lets crete x and y man
x=torch.tensor([[1,3,4],[2,4,5],[3,5,6],[4,5,6],[5,6,8],[1,3,4],[2,4,3],[3,4,5],[4,5,6],[5,5,6]])
y=torch.tensor([200,300,240,345,560,234,456,324,345,678])

#lets create them as the tensordataset
data=TensorDataset(x,y)

#creating dataloader
loader=DataLoader(data,batch_size=2,shuffle=True)

#now we nend create the instances for loss function , optimizer , activation
#it is linear so lets use the mse
loss=MSELoss()
relu=ReLU()
tanh=Tanh()
#optimizer=Adam(lr=0.02, params=)

   #now layers
cf1=nn.Linear(3,5)
cf2=nn.Linear(5,3)
cf3=nn.Linear(3,1)

optimizer=Adam(lr=0.02, params=[cf1.model_parameters(),cf2.model_parameters(),cf3.model_parameters()])

#now lets creae the moddel arrrangement

def forward(input):
  hidden=cf1(input)
  act1=relu(hidden)
  hidden=cf2(act1)
  act2=tanh(hidden)
  output=cf3(act2)
  return output

def train(epochs):
  for i in range(epochs):
    #batches in that epoch as loader gives one batch at a time
    for x_train,y_train in loader:
      x,y=x_train,y_train
      output=forward(x)

      #now predicting
      loss=loss(output,y)
      loss.backward()
      optimizer.step()
      optimizer.zero_grad()

train(3)






AttributeError: 'Linear' object has no attribute 'model_parameters'

In [79]:
x=torch.tensor([[1,3,4],[2,4,5],[3,5,6],[4,5,6],[5,6,8],[1,3,4],[2,4,3],[3,4,5],[4,5,6],[5,5,6]],dtype=torch.float32)
y=torch.tensor(
    [[200.],[300.],[240.],[345.],[560.],
     [234.],[456.],[324.],[345.],[678.]]
)

#pytorch uses float tensors
#lets create them as the tensordataset
data=TensorDataset(x,y)

#creating dataloader
loader=DataLoader(data,batch_size=2,shuffle=True)

#now we nend create the instances for loss function , optimizer , activation
#it is linear so lets use the mse
criterion=MSELoss()
relu=ReLU()
tanh=Tanh()
#optimizer=Adam(lr=0.02, params=)

   #now layers
cf1=nn.Linear(3,5)
cf2=nn.Linear(5,3)
cf3=nn.Linear(3,1)

optimizer=Adam(lr=0.02, params=list(cf1.parameters())+list(cf2.parameters())+list(cf3.parameters()))

#there iss no model_parameters , we use parameters and it als return genrator soo
#we dont want list of list of generator of parameters  so we use this approach

#now lets creae the moddel arrrangement

def forward(input):
  hidden=cf1(input)
  act1=relu(hidden)
  hidden=cf2(act1)
  act2=tanh(hidden)
  output=cf3(act2)
  return output

def train(epochs):
  for i in range(epochs):
    #batches in that epoch as loader gives one batch at a time
    for x_train,y_train in loader:
      x,y=x_train,y_train
      output=forward(x)

      #now predicting
      loss=criterion(output,y)
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      print(
    f"Epoch {i+1}, Loss={loss.item()}"
)

train(3)

Epoch 1, Loss=386825.0
Epoch 1, Loss=112046.484375
Epoch 1, Loss=86888.09375
Epoch 1, Loss=132712.75
Epoch 1, Loss=64923.04296875
Epoch 2, Loss=156278.078125
Epoch 2, Loss=256943.390625
Epoch 2, Loss=215968.53125
Epoch 2, Loss=64772.0546875
Epoch 2, Loss=88001.21875
Epoch 3, Loss=55890.9140625
Epoch 3, Loss=201215.59375
Epoch 3, Loss=332954.875
Epoch 3, Loss=79059.96875
Epoch 3, Loss=111394.171875


In [104]:
'''/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([2, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)'''

'''
RuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float'''


'\nRuntimeError: mat1 and mat2 must have the same dtype, but got Double and Float'

In [81]:

def forward(input):
  hidden=cf1(input)
  act1=relu(hidden)
  hidden=cf2(act1)
  act2=tanh(hidden)
  output=cf3(act2)
  return output

#see instead of using again diff forward function fro passing output to sequential layers we can use the
#nn.Sequential layer
model = nn.Sequential(
    nn.Linear(3,5),
    nn.ReLU(),
    nn.Linear(5,3),
    nn.Tanh(),
    nn.Linear(3,1)
)

#now simply
output = model(x)

In [87]:
#now lets do binary class in binary class
#as weknow we use loss function binatry cross entropy or crossentropy or binraycrossentropy withlogits(mostly preferred)


from torch.nn import BCEWithLogitsLoss,Sigmoid


x=torch.tensor([[1,3,4],[2,4,5],[3,5,6],[4,5,6],[5,6,8],[1,3,4],[2,4,3],[3,4,5],[4,5,6],[5,5,6]],dtype=torch.float32)
y=torch.tensor(
    [[1.],[0.],[1.],[0.],[1.],
     [1.],[1.0],[0.],[0.],[1.]]
)

#pytorch uses float tensors
#lets create them as the tensordataset
data=TensorDataset(x,y)

#creating dataloader
loader=DataLoader(data,batch_size=2,shuffle=True)

#now we nend create the instances for loss function , optimizer , activation
#it is linear so lets use the mse
criterion=BCEWithLogitsLoss()
relu=ReLU()
tanh=Tanh()
sigmoid=Sigmoid()
#optimizer=Adam(lr=0.02, params=)


model = nn.Sequential(
    nn.Linear(3,5),
    nn.ReLU(),
    nn.Linear(5,3),
    nn.Sigmoid(),
    nn.Linear(3,1)
)

optimizer=Adam(lr=0.02, params=model.parameters())

#there iss no model_parameters , we use parameters and it als return genrator soo
#we dont want list of list of generator of parameters  so we use this approach

#now lets creae the moddel arrrangement



def train(epochs):
  for i in range(epochs):
    #batches in that epoch as loader gives one batch at a time
    for x_train,y_train in loader:
      x,y=x_train,y_train
      logits=model(x)
      #now predicting
      loss=criterion(logits,y)   #here the loss function taking This loss combines a Sigmoid layer and the BCELoss in one single class.
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      print(
    f"Epoch {i+1}, Loss={loss.item()}"
)

train(3)

Epoch 1, Loss=0.6172012090682983
Epoch 1, Loss=0.7020734548568726
Epoch 1, Loss=0.7016499042510986
Epoch 1, Loss=0.7031676173210144
Epoch 1, Loss=0.7051132917404175
Epoch 2, Loss=0.7048075795173645
Epoch 2, Loss=0.5541011095046997
Epoch 2, Loss=0.7063573002815247
Epoch 2, Loss=0.7070608139038086
Epoch 2, Loss=0.7071042656898499
Epoch 3, Loss=0.7075111865997314
Epoch 3, Loss=0.5357799530029297
Epoch 3, Loss=0.7094213962554932
Epoch 3, Loss=0.7101033329963684
Epoch 3, Loss=0.7105801105499268


In [85]:
model = nn.Sequential(
    nn.Linear(3,5),
    nn.ReLU(),
    nn.Linear(5,3),
    nn.Sigmoid(),
    nn.Linear(3,1)
)
model.parameters()
for i in model.parameters():
  print(i)                       #randomly intiakized at the time of layer creation itself

Parameter containing:
tensor([[-0.5695, -0.5060,  0.5258],
        [ 0.1696,  0.1369, -0.1092],
        [ 0.5012,  0.1058,  0.3080],
        [-0.2393, -0.2724, -0.2225],
        [ 0.3811,  0.4706,  0.2462]], requires_grad=True)
Parameter containing:
tensor([ 0.0140,  0.0268, -0.0312,  0.0035, -0.4752], requires_grad=True)
Parameter containing:
tensor([[-0.1548,  0.1399,  0.0615, -0.4321, -0.3789],
        [-0.3452,  0.4365, -0.2768,  0.2678, -0.0295],
        [ 0.3770, -0.1660,  0.1012, -0.1205, -0.4242]], requires_grad=True)
Parameter containing:
tensor([ 0.4220, -0.4185, -0.0912], requires_grad=True)
Parameter containing:
tensor([[0.0962, 0.3729, 0.2659]], requires_grad=True)
Parameter containing:
tensor([0.2121], requires_grad=True)


In [116]:
#for multiclass see we dont really use the OHE
#like in tensorflow we use like categorical cross entropy for OHE
#AND sparse  categorovcal cross entropy for the label encoding

#here we use the cross netropy that actually use the label encoding (0,1,2,3)

#now lets do that

#before that see lets again recatch the sklearn basics man
#now we have datasets in the sklearn

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from torch.nn import CrossEntropyLoss
from torch.optim import Adam
from torch import argmax
from torch.utils.data import TensorDataset

data=load_iris(
)

data

x=data.data
y=data.target

print("x_features:",x[0],type(x))
print("y_features",y[0],type(y))
#they both are  numpy arrays


#now lets do scaling beforewe do scaling we ahve to split them to tarin,test,split nah

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=32)

scalar=StandardScaler()

#now fitting
x_train_scaled=scalar.fit_transform(x_train)
x_test_scaled=scalar.transform(x_test)


x_torch=torch.tensor(x_train_scaled,dtype=torch.float32) #thesse should be in the float
y_torch=torch.tensor(y_train,dtype=torch.long)   #see the cross entropy expects of labelled data in integers  not float




#now the remaing task is very simple man
#again do same task
model=nn.Sequential(

    nn.Linear(4,5),
    nn.ReLU(),
    nn.Linear(5,6),
    nn.Tanh(),
    nn.Linear(6,3)

)

criterion=CrossEntropyLoss()
adam=Adam(lr=0.05,params=model.parameters())

#dataset
data=TensorDataset(x_torch,y_torch)
#loader
loader=DataLoader(data,batch_size=30)

def train(epochs):
  for i in range(epochs):
    for x,y in loader:
      logits=model(x)  #if we want which class then we can simply use the argmax over logits
      loss=criterion(logits,y)
      adam.zero_grad()
      loss.backward()
      adam.step()

    print(f'loss in epoch{i} is {loss}')



def predict(x):
  with torch.no_grad():   #anyway we using the adam.zero_grad() during traing so no worries
    logits=model(x)
  #we will get list of logits
  #now finding argmax (max values index in row-wise)
  index=argmax(logits,dim=1)
  print(logits)
  print(index,'nothing but class itself ')



train(6)




x_features: [5.1 3.5 1.4 0.2] <class 'numpy.ndarray'>
y_features 0 <class 'numpy.ndarray'>
loss in epoch0 is 0.6423073410987854
loss in epoch1 is 0.39140814542770386
loss in epoch2 is 0.2549193203449249
loss in epoch3 is 0.18849168717861176
loss in epoch4 is 0.1413990557193756
loss in epoch5 is 0.08907798677682877


In [137]:
#lets see the prediction
x_test_tensor=torch.tensor(x_test_scaled,dtype=torch.float32)

type(x_test_tensor)
type(x_test_tensor[0])

#both are tensors only

#print(x_test_tensor[0][0]) #still a tensor of scalar

#now lets do the prediction

predict(x_test_tensor[[20]])

#print(x_test_tensor[[0]])  #it is accepting in the (batch,input)

#now lets see is it correct
print('actual class-->',y_test[20])


tensor([[ 5.2742,  0.8813, -5.3207]])
tensor([0]) nothing but class itself 
actual class--> 0


In [146]:
'''with torch.no_grad():
    logits = model(x_test_torch)
    preds = torch.argmax(logits, dim=1)

accuracy = (preds == y_test_torch).float().mean()

print("Accuracy:", accuracy.item())'''

print("better preduction pipeline ")

import  torch
arr=torch.tensor([1,2,3])
arr2=torch.tensor([1,2,2])
print(arr==arr2)
print((arr==arr2).int())   #it does element wise comparision
#to do means the type should be float , decimal or complex
(arr==arr2).float().mean()

#it actually doing ike this (correct predicted ons sum)/(total) --> which itself is accuracy


better preduction pipeline 
tensor([ True,  True, False])
tensor([1, 1, 0], dtype=torch.int32)


tensor(0.6667)

In [ ]:
#now lets predict the model


In [98]:
"This criterion computes the cross entropy loss between input logits and target."
#some information about the CrossEntropyLoss
#se this gets logits no need to be the sigmoid act to apply on nodes

#se the CrossEntropyLoss itself inbuilt does the things
#-->LogSoftmax   +
#Negative Log Likelihood

#see like taht BCEwithlogits too does the thing internally it does the
#sigmoid +
#binarycrossentropyLoss (BCELoss)

#so this both takes logits as input
#but if you use  the BCELoss then you have send sigmoid output to the BCELoss
#x=linear(3,1)
#sigmoid(x) then this values we will pass to the BCELoss


'This criterion computes the cross entropy loss between input logits and target.'

In [147]:
#now lets go for some training and eval mode
#why because see normally we sue dropout and batchnorm
#while training we make use of dropout and batchnorm to update it statistics
#but during eval we use the updated statitics and dont amke any update and the dropout too like to not use it fully dense

#so  in built we have .eval() for telling this behaviour to model lie ok we doing forward pass for evaluation so consider that
#so .train() tells ok we doing forwaards pass to train the model so make use of tahtbehaviour


#like that lets see


'''the architecture is still same



model = nn.Sequential(
    nn.Linear(4,8),
    nn.ReLU(),
    nn.Dropout(0.5),
    nn.Linear(8,3)
)




for epoch in range(epochs):

    # TRAIN
    model.train()

    for x, y in train_loader:

        ...
        loss.backward()
        optimizer.step()

    # VALIDATION
    model.eval()

    with torch.no_grad():

        for x, y in val_loader:

            ...'''

print('make use of this architecture while doing the training')

make use of this architecture while doing the training


In [148]:
#now lets learn freezing , unfreezing the model and adding new layers to the model by removing layers and again finetuning lets do that tasks
#later we can move to big nueral netwrok like transformers

In [167]:
#now first lets do freezing
model = nn.Sequential(
    nn.Linear(4, 16),   # layer 0
    nn.ReLU(),
    nn.Linear(16, 8),   # layer 2
    nn.ReLU(),
    nn.Linear(8, 3)     # layer 4
)

#now lets freeze the layer1

for i in model.named_parameters():
  print(i)
  print()


#like see their name is like 0,1,2 we acces through [] and form gtaht do we wanr weights or bias
model[0].weight

#lets make

model[0].requires_grad=False  #we are making entire layer requires_grad=False , so their grad computation dont get stores

#let check
for i in model.parameters():
  #it goes layer by layer
  print(i.requires_grad)

('0.weight', Parameter containing:
tensor([[ 0.1540,  0.1985,  0.2466,  0.0409],
        [-0.1820, -0.1869, -0.2610,  0.3522],
        [ 0.1771,  0.1325,  0.2994,  0.4470],
        [-0.3801,  0.4900,  0.2350,  0.2360],
        [ 0.1388,  0.2551, -0.2912, -0.0341],
        [ 0.4847,  0.3643,  0.4120, -0.3318],
        [ 0.4001,  0.2551,  0.4504,  0.3001],
        [-0.2300, -0.2536, -0.4755, -0.0070],
        [-0.1756,  0.2038,  0.1909,  0.1649],
        [-0.1119,  0.1976,  0.2827,  0.3196],
        [-0.4034, -0.0269, -0.2205, -0.4642],
        [ 0.1239,  0.0073, -0.3033, -0.1012],
        [ 0.4299,  0.1219, -0.3485, -0.0603],
        [ 0.0166,  0.0171, -0.1110, -0.2262],
        [-0.1145, -0.1411, -0.2905, -0.2424],
        [ 0.2057, -0.2206, -0.4494, -0.4318]], requires_grad=True))

('0.bias', Parameter containing:
tensor([ 0.4094,  0.0303,  0.0426,  0.1163, -0.3852,  0.2737, -0.4367, -0.2817,
        -0.2101,  0.3009,  0.4509, -0.1172, -0.2921, -0.1487,  0.4768, -0.2185],
       requi

In [175]:
#the above not works because when we do model[0] we accesing at layer level
#the requires_grad not works at layer level it works on parm level
#so we need to do like this

#for whole model freezing

for i in model.parameters():
  i.requires_grad=False  #see here we accesing at param level

#or for partcular layer if you want to do

for i in model[0].parameters():
  i.requires_grad=True

#lets check
for i,j in model.named_parameters():
  print(j.requires_grad,i)

True 0.weight
True 0.bias
False 2.weight
False 2.bias
False 4.weight
False 4.bias


In [177]:
'''1. Slicing in nn.Sequential

Suppose:

model = nn.Sequential(
    nn.Linear(4,16),  # 0
    nn.ReLU(),        # 1
    nn.Linear(16,8),  # 2
    nn.ReLU(),        # 3
    nn.Linear(8,3)    # 4
)

Access single layer:

model[0]
model[2]

You can also slice:

model[:2]

Output:

Sequential(
  (0): Linear(4,16)
  (1): ReLU()
)
model[:-1]

Output:

Sequential(
  (0): Linear(4,16)
  (1): ReLU()
  (2): Linear(16,8)
  (3): ReLU()
)

Very useful for removing classifier heads.

Example:

backbone = model[:-1]

Now:

x = backbone(x)

runs everything except the last layer.

This is a common transfer learning trick.

2. Freezing with slices

Freeze first 3 modules:

for layer in model[:3]:
    for p in layer.parameters():
        p.requires_grad = False

Freeze everything except last layer:

for layer in model[:-1]:
    for p in layer.parameters():
        p.requires_grad = False

Very clean.

3. Custom layer names inside Sequential

Instead of:

model[0]
model[2]
model[4]

you can give names.

Use OrderedDict:

from collections import OrderedDict

model = nn.Sequential(
    OrderedDict([
        ("fc1", nn.Linear(4,16)),
        ("relu1", nn.ReLU()),
        ("fc2", nn.Linear(16,8)),
        ("relu2", nn.ReLU()),
        ("classifier", nn.Linear(8,3))
    ])
)

Now:

model.fc1

❌ Doesn't work.

Sequential doesn't create attributes.

Instead:

model["fc1"]
model["classifier"]

✅ Works.

Check names:

for name, module in model.named_children():
    print(name)

Output:

fc1
relu1
fc2
relu2
classifier
4. Real-world approach: use nn.Module

Once models get bigger, people stop using numeric indexing.

Instead:

class MyNet(nn.Module):

    def __init__(self):
        super().__init__()

        self.encoder = nn.Sequential(
            nn.Linear(4,16),
            nn.ReLU(),
            nn.Linear(16,8)
        )

        self.classifier = nn.Linear(8,3)

    def forward(self,x):

        x = self.encoder(x)
        x = self.classifier(x)

        return x

Now you get beautiful names:

model.encoder
model.classifier

Freeze encoder:

for p in model.encoder.parameters():
    p.requires_grad = False

Replace classifier:

model.classifier = nn.Linear(8,5)

This is exactly how transformer models are structured:

model.encoder
model.decoder
model.classifier
model.lm_head
model.embeddings'''

print('see how to write convential names')

see how to write convential names


In [179]:
''''First, OrderedDict is just a dictionary that preserves insertion order.

from collections import OrderedDict

model = nn.Sequential(
    OrderedDict([
        ("fc1", nn.Linear(4,16)),
        ("relu1", nn.ReLU()),
        ("fc2", nn.Linear(16,8)),
        ("relu2", nn.ReLU()),
        ("classifier", nn.Linear(8,3))
    ])
)  '''

print('usage of ordereddict')

print(' but mostlywe should not ue like this see above last  part of above cell')

usage of ordereddict
 but mostlywe should not ue like this see above last  part of above cell


In [180]:
#see the important that we need to remember evryone
#is see yeah we can freeze the layers of parameters
#but the thing is sequentual model is it self id built on the top of nn.module

#we basically use  the nn.Module
#it will do all ting regestring layers , params etc..,

#but the thing that we can do wiith the sequrnail moel as it build on the nn.Modue it self
#but the nn.Module inheriting give suse vey flexibility
